// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuauQltvc79P8piE-lY6_3TPYeFqQyHo',
    appId: '1:811418683839:android:3785697033e055bed7790a',
    messagingSenderId: '811418683839',
    projectId: 'chat-modelo-67226',
    storageBucket: 'chat-modelo-67226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7vyie1nMgNo-oOjTQHsnL2wl9LdzF104',
    appId: '1:811418683839:ios:bc70cc2a29c81cf2d7790a',
    messagingSenderId: '811418683839',
    projectId: 'chat-modelo-67226',
    storageBucket: 'chat-modelo-67226.appspot.com',
    androidClientId: '811418683839-s7q41nmlg3fld99lh2pqnluhf562gvho.apps.googleusercontent.com',
    iosClientId: '811418683839-b5eopt4tg5aqv7v3s11ct28keui4n6j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNzWmnaY_7FE4HAB7t59IJo0rszKITFyE',
    appId: '1:811418683839:web:a14bd161f00c3f41d7790a',
    messagingSenderId: '811418683839',
    projectId: 'chat-modelo-67226',
    authDomain: 'chat-modelo-67226.firebaseapp.com',
    storageBucket: 'chat-modelo-67226.appspot.com',
  );

}